DROP TABLE User IF EXISTS;
DROP TABLE Worker IF EXISTS;
DROP TABLE Client IF EXISTS;
DROP TABLE Task IF EXISTS;
DROP TABLE Task_type IF EXISTS;
DROP TABLE Object IF EXISTS;
DROP TABLE Report IF EXISTS;
DROP TABLE Material IF EXISTS;
DROP TABLE Responsible_person IF EXISTS;
DROP TABLE Image IF EXISTS;

CREATE TABLE User (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  email VARCHAR(200) NOT NULL,
  name VARCHAR(200),
  password VARCHAR(200) NOT NULL,
  companyName VARCHAR(200),
  isver BOOLEAN,
  PRIMARY KEY(id)
);

CREATE TABLE Worker (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  email VARCHAR(200),
  name VARCHAR(200),
  password VARCHAR(200),
  created VARCHAR(200),
  updated VARCHAR(200),
  lat DOUBLE,
  lng DOUBLE,
  isactive boolean,
  PRIMARY KEY(id)
);

CREATE TABLE Client (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200),
  code VARCHAR(200),
  address VARCHAR(200),
  phone VARCHAR(200),
  PRIMARY KEY(id)
);

CREATE TABLE Task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  title VARCHAR(200) NOT NULL,
  planned_time VARCHAR(200) NOT NULL,
  planned_end_time VARCHAR(200),
  client VARCHAR(200) NOT NULL,
  object VARCHAR(200) NOT NULL,
  worker VARCHAR(200),
  description VARCHAR(500),
  
  signed_by VARCHAR(200),
  agreed BOOLEAN,
  rating INTEGER,
  agreement boolean,
  signature_type INTEGER,
  abort_message VARCHAR(200),
  client_note VARCHAR(200),
  client_note_reply VARCHAR(200),
  distance INTEGER,
  work_price INTEGER,
  material_price INTEGER,
  final_price INTEGER,
  status INTEGER,
  fetched BOOLEAN,
  start_time VARCHAR(200),
  total_time_start BIGINT,
  total_time BIGINT,
  end_time VARCHAR(200),
  start_on_time BOOLEAN,
  duration BIGINT,
  bill_status BOOLEAN,
  bill_date VARCHAR(200),
  file_exists BOOLEAN,
  signature_exists BOOLEAN,
  task_type BIGINT,
  created VARCHAR(200),
  updated VARCHAR(200),
  PRIMARY KEY(id));
	
CREATE TABLE Task_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  title VARCHAR(200) NOT NULL,
  mail_list VARCHAR(200),
  signature BOOLEAN,
  created VARCHAR(200),
  updated VARCHAR(200),
  PRIMARY KEY(id)
);

CREATE TABLE Object (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(200) NOT NULL,
  address VARCHAR(200),
  client VARCHAR(200) NOT NULL,
  lat DOUBLE,
  lng DOUBLE,
  PRIMARY KEY(id)
);

CREATE TABLE Report (
  id int,
  company_name VARCHAR(200),
  company_code VARCHAR(200),
  company_address VARCHAR(200),
  company_phone VARCHAR(200),
  report_text VARCHAR(500),
  show_price BOOLEAN,
  show_description BOOLEAN,
  show_start BOOLEAN,
  show_finish BOOLEAN,
);

CREATE TABLE Material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(200) NOT NULL,
  unit VARCHAR(200) NOT NULL,
  price DOUBLE NOT NULL,
  quantity BIGINT,
  location VARCHAR(200),
  time_used VARCHAR(200),
  used boolean,
  task BIGINT,
  PRIMARY KEY(id)
);



CREATE TABLE Responsible_person (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  first_name VARCHAR(200) NOT NULL,
  last_name VARCHAR(200) NOT NULL,
  phone VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  client BIGINT NOT NULL,
  created VARCHAR(200),
  updated VARCHAR(200),
  PRIMARY KEY(id)
);

CREATE TABLE Image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(200),
  path VARCHAR(200),
  task BIGINT,
  created VARCHAR(200),
  PRIMARY KEY(id)
);

CREATE TABLE Signature (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(200),
  path VARCHAR(200),
  task BIGINT,
  created VARCHAR(200),
  PRIMARY KEY(id)
);